name: versioning

on:
  push:
    branches: ["main"]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Bump Version
        run: make bump
        env:
          BUILD_VERSION: v${{ steps.gitversion.outputs.MajorMinorPatch }}-rc${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
      - name: Commit Version Bump
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "chore: [skip ci] bump version to v${{ steps.gitversion.outputs.MajorMinorPatch }}-rc${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
